# Generated by Django 4.1.4 on 2023-03-07 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategoriya nomini kiriting', max_length=200, unique=True, verbose_name='Kategoriya nomi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Kategoriyalar',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(help_text='Yetkazib berish narxini kiriting', verbose_name='Yetkazib berish narxi')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name="Ohirgi martta o'zgartirilgan sana")),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('Naqd pul', 'cash'), ('Click', 'click'), ('Payme', 'payme')], max_length=20, verbose_name="To'lov turi")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.CharField(max_length=50, verbose_name='Umumiy narx')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Buyurtmalar',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='Nickname')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram id')),
                ('user_lang', models.CharField(max_length=5, verbose_name='Tili')),
                ('user_phone', models.CharField(max_length=20, unique=True, verbose_name='Raqam')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tovar nomini kiriting', max_length=500, verbose_name='Nomi')),
                ('descr', models.TextField(help_text="Tovar haqida qo'shimcha ma'lumot", verbose_name='Tavsif')),
                ('price', models.PositiveBigIntegerField(default=0, help_text='Tovar narxini kiriting', verbose_name='Narx')),
                ('measure', models.CharField(choices=[('dona', 'quan'), ('kg', 'kg')], help_text='1 dona non, yoki 1 kg olma', max_length=20, verbose_name="O'lchov, birlig")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('cat', models.ForeignKey(help_text='Tovar kategoriyasini tanlang', on_delete=django.db.models.deletion.CASCADE, to='qoyliq_app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Tovarlar',
                'verbose_name_plural': 'Tovarlar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quan', models.IntegerField(verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qoyliq_app.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qoyliq_app.product', verbose_name='Tovar')),
            ],
            options={
                'verbose_name': 'Buyurtma tovarlar',
                'verbose_name_plural': 'Buyurtma tovarlar',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qoyliq_app.user', verbose_name='Xaridor'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qoyliq_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qoyliq_app.user')),
            ],
        ),
    ]
