# Generated by Django 4.1.4 on 2023-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoyliq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('dona', 'dona'), ('kg', 'kg')], help_text='1 dona non, yoki 1 kg olma', max_length=20, verbose_name="O'lchov, birlig"),
        ),
    ]
