# Generated by Django 4.1.4 on 2023-03-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoyliq_app', '0002_alter_product_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
