# Generated by Django 4.1.4 on 2023-03-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoyliq_app', '0004_orderitem_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order',)},
        ),
    ]
