# Generated by Django 4.1.4 on 2023-03-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoyliq_app', '0006_alter_orderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quan',
            new_name='quantity',
        ),
    ]
