# Generated by Django 4.1.4 on 2023-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoyliq_app', '0007_rename_quan_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Aloqa uchun raqamlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': "Bog'lanish uchun",
                'verbose_name_plural': "Bog'lanish uchun",
            },
        ),
        migrations.AlterModelOptions(
            name='deliveryprice',
            options={'verbose_name': 'Yetkazib berish naxi', 'verbose_name_plural': 'Yetkazib berish naxi'},
        ),
    ]
